### ISSUE TITLE
Linebreaks after inline-blocks

### ISSUE THREAD

**Issue by michaelLoeffelmann** [Anivive/vue-contentful-rich-text#1]
**Describe the bug**
When the RichtTextField contains some inline elements like `<em> <strong> or <u>` it will adds a `<br>` before and after the element. How can i avoid this behaviour?

**To Reproduce**
1. Add some Text to RichtText-Field in Contentful
2. Select a text sequence an make it "strong" for example

**Expected behavior**
The strong element should appear in the text without linebreaks.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 100.0.4896.127

**Comment by michaelLoeffelmann** [comment]
Maybe you can add something like this in line 65:

``` 
let fragments = node.value.split(/\n/g);

if (fragments.length > 1) {
  fragments.forEach((item, index) => {
    handledValue.push(item);
    if (index !== fragments.length - 1) {
      handledValue.push(h("br"));
    }
  });
} else {
  handledValue.push(node.value);
}
```

**Comment by SkylerStearns** [comment]
Hi @LrMiLoef,

Thank you for submitting this bug for our review. We've actually stopped actively working on this project, so we aren't going to be able to work to research/resolve your issue. I've spoken with our team, and we will try to add a tag saying that this project is archived.

My suggestion would be that you either create a workaround to resolve your issue, or if you want to submit a PR, we might be able to take a look. Realistically, since this isn't really in our scope of work anymore, it may or may not be accepted.

All in all, we really appreciate your input and feedback.

Thank you,
Skyler @Anivive
